### PR TITLE
Enable to use gem mysql2 0.4.x

### PR DESCRIPTION
**Pull request by key-amb**
Hi,

As far as I run tests at my Mac OSX PC with ruby v2.3.1 and latest mysql2 v0.4.5, there seems to be no problem.
If you accept this patch, I will be happier.

Thanks,

### CODE REVIEW

**Comment by ryopeko** [comment]
Thank you for your contribution. 😄 

Why did you specific version 0.5?
mysql2 doesnot use semantic versioning.
https://rubygems.org/gems/mysql2/versions

rubygems's version has a syntax of '~>'.
"~> 0.4.5" include '0.4.x' .

**Comment by key-amb** [comment]
Thank you for your reply.

> Why did you specific version 0.5?

This change is from Gemfile of rails app which is made by `rails new x -d mysql`:

```
# In case rails 4.2.6
% rails new foo -d mysql
% grep mysql2 foo/Gemfile
gem 'mysql2', '>= 0.3.13', '< 0.5'

# In case rails 5.0.0
% rails new bar -d mysql
% grep mysql2 bar/Gemfile
gem 'mysql2', '>= 0.3.18', '< 0.5'
```

I think it's better for people using older `mysql2` of `0.3.x` not to force upgrade to `0.4.x`.

As for **me**, it's no problem if it shall be `'~> 0.4.5'`.

**Comment by ryopeko** [comment]
I got it.
Thank you 😄

**Comment by ryopeko** [comment]
Released as v0.6.0 🎉

**Comment by key-amb** [comment]
Thank you!

**Pull request merged**
